### ISSUE TITLE
RSTATIC#1: deploy 'rstatic' host

### ISSUE THREAD

**Issue by joseosuna** [jtogaf/rstatic#1]
# Details
**Story Points:**  1 point.

# Description
We need a host to deploy our static resources such as logos, images, docs and others. Our host most be located in http://rstatic.jtogaf.com.

**User:** Search engines.
**I Want:** Static information about the website is enabled.
**In order to:** Search engines can read it.

**Criteria:**
1. Write URI in a browser and verify each static resource is enabled.

**Examples:**
http://rstatic.jtogaf.com/logo.gif. 
http://rstatic.jtogaf.com/copyright.xhtml

# Issue Links
**Cloners**
This issue *clones*:
[RSTATIC#1: deploy 'rstatic' host](https://github.com/reddepruebas/rstatic/issues/1)

# Sub-Tasks
1. [x] [RSTATIC#2: Create a Jboss 7.1 engine in OpenShift.](https://github.com/jtogaf/rstatic/issues/2)
2. [x] [RSTATIC#3: Add an alias in Open Shift.](https://github.com/jtogaf/rstatic/issues/3)
3. [x] [RSTATIC#4: Add a CNAME in DNS hosting.](https://github.com/jtogaf/rstatic/issues/4)
4. [x] [RSTATIC#5: Clone Open Shift Project.](https://github.com/jtogaf/rstatic/issues/5)
5. [x] [RSTATIC#6: Load static resources.](https://github.com/jtogaf/rstatic/issues/6)
6. [x] [RSTATIC#7: Link code to GitHub.](https://github.com/jtogaf/rstatic/issues/7)

# Time Tracking
**Date Started:** May 04, 2015.
**Time Spent:** *(eg. 3w 4d 12h)* 6h 20m.
